---
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: a-routes
  namespace: httpbin
  labels:
    domain: httpbin.demo.mtritaba.com
spec:
  routes:
  - matchers:
     # the path matchers in this RouteTable can begin with any prefix
    - prefix: /app-a
    routeAction:
      single:
        upstream:
          name: 'httpbin-httpbin-8000'
    options:
      prefixRewrite: '/'
